version: '3.8'

services:
  # The Target API
  api:
    image: wallet-lab-api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=secret123
      - DB_NAME=wallet_db
    depends_on:
      - db
    networks:
      - void_net
    volumes:
      - ./src:/app/src  # Syncs your code live so you don't rebuild every time
      - /app/node_modules

  # The Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: wallet_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - void_net

networks:
  void_net:
    driver: bridge